import crypto from 'crypto';
import { pool, query } from '../../config/db.js';
import { ApiError } from '../../utils/ApiError.js';
import { allocateDocumentNumber } from './inventory-document-number.service.js';
import { getSubmissionSnapshotExtension, validateDocumentForSubmission } from './inventory-document-validation.service.js';
import { decimal } from './inventory-decimal.js';

const TYPES = new Set(['GOODS_RECEIPT','STOCK_COUNT','INVENTORY_ADJUSTMENT','WASTE_LOSS','PREPARATION_PRODUCTION','PRODUCT_PRODUCTION','STORE_TRANSFER','REVERSAL']);
const EDITABLE = new Set(['DRAFT','REJECTED']);

const clean = (v) => typeof v === 'string' ? v.trim() : '';
const actorId = (actor) => clean(actor?.id) || (() => { throw new ApiError(401, 'Actor is required.'); })();
function canonical(value) { if (Array.isArray(value)) return `[${value.map(canonical).join(',')}]`; if (value && typeof value === 'object') return `{${Object.keys(value).sort().map((k)=>`${JSON.stringify(k)}:${canonical(value[k])}`).join(',')}}`; return JSON.stringify(value); }
const nullableText = (value) => value === null || value === undefined ? null : String(value);
const nullableDecimal = (value) => value === null || value === undefined ? null : decimal(value, 'Submitted decimal');
function submittedGenericLine(line) { return {
  id: nullableText(line.id ?? line.document_item_id), lineNumber: Number(line.line_number), inventoryItemId: nullableText(line.inventory_item_id), itemRole: nullableText(line.item_role), baseQuantity: nullableDecimal(line.base_quantity),
  itemNameSnapshot: nullableText(line.item_name_snapshot ?? line.current_item_name), baseUnitSnapshot: nullableText(line.base_unit_snapshot ?? line.current_base_unit), storageLocationNameSnapshot: nullableText(line.storage_location_name_snapshot ?? line.current_location_name), note: nullableText(line.note),
}; }
const normalizedTimestamp = (value) => value === null || value === undefined ? null : new Date(value).toISOString();
export function hashDocumentSubmissionSnapshot(snapshot) { return crypto.createHash('sha256').update(canonical(snapshot)).digest('hex'); }
// This is the sole canonical submitted-document envelope. Every submit and every approval
// verification uses this exact stable shape; callers may supply either receipt-detail or generic
// line rows because submittedGenericLine normalizes their persisted identities identically.
export function buildSubmittedDocumentSnapshot({ document, genericLines, typedPayload, revision }) { return { documentNumber: nullableText(document.document_number), documentType: nullableText(document.document_type), revision: Number(revision), note: nullableText(document.note), effectiveAt: normalizedTimestamp(document.effective_at), genericLines: [...genericLines].map(submittedGenericLine).sort((a,b) => a.lineNumber - b.lineNumber || String(a.id).localeCompare(String(b.id))), typedPayload: typedPayload ?? null }; }
export async function buildDocumentSubmissionSnapshot(document, lines, revision, client) { return buildSubmittedDocumentSnapshot({ document, genericLines: lines, revision, typedPayload: await getSubmissionSnapshotExtension(document, lines, client) }); }
function normalizeLines(lines) {
  if (!Array.isArray(lines)) return [];
  const seen = new Set();
  return lines.map((line,index)=>{ const inventoryItemId=clean(line.inventoryItemId ?? line.inventory_item_id); if(!inventoryItemId) throw new ApiError(400,`Line ${index+1} inventory item is required.`); const lineNumber=Number(line.lineNumber ?? line.line_number ?? index+1); if(!Number.isInteger(lineNumber)||lineNumber<1||seen.has(lineNumber)) throw new ApiError(400,'Line numbers must be unique positive integers.'); seen.add(lineNumber); return {inventoryItemId,lineNumber,itemRole:clean(line.itemRole ?? line.item_role).toUpperCase()||'PRIMARY',baseQuantity:line.baseQuantity ?? line.base_quantity ?? null,note:clean(line.note)||null}; });
}
async function addEvent(client, { documentId, actorId: userId, type, fromStatus=null, toStatus=null, revision, reason=null, hash=null, payload={} }) { await client.query(`insert into inventory_document_events(document_id,event_type,actor_id,from_status,to_status,document_revision,reason,content_hash,event_payload) values($1,$2::inventory_document_event_type,$3,$4::inventory_document_status,$5::inventory_document_status,$6,$7,$8,$9::jsonb)`,[documentId,type,userId,fromStatus,toStatus,revision,reason,hash,JSON.stringify(payload)]); }
async function loadDocument(client,id,storeId,lock=false) { const result=await client.query(`select * from inventory_documents where id=$1 and store_id=$2 ${lock?'for update':''}`,[id,storeId]); if(!result.rows[0]) throw new ApiError(404,'Inventory document not found.'); return result.rows[0]; }
async function loadLines(client,id) { return (await client.query(`select di.*,coalesce(i.name,p.name) as current_item_name,bu.name as current_base_unit,sl.name as current_location_name from inventory_document_items di join inventory_items ii on ii.id=di.inventory_item_id and ii.store_id=di.store_id left join ingredients i on i.id=ii.ingredient_id left join products p on p.id=ii.product_id left join inventory_item_units bu on bu.inventory_item_id=ii.id and bu.is_base left join storage_locations sl on sl.id=ii.storage_location_id where di.document_id=$1 order by di.line_number`,[id])).rows; }
async function replaceLines(client, document, lines) { await client.query(`delete from inventory_document_items where document_id=$1`,[document.id]); for(const line of lines) await client.query(`insert into inventory_document_items(document_id,store_id,line_number,inventory_item_id,item_role,base_quantity,note) values($1,$2,$3,$4,$5::inventory_document_item_role,$6::numeric,$7)`,[document.id,document.store_id,line.lineNumber,line.inventoryItemId,line.itemRole,line.baseQuantity,line.note]); }
export async function createDocument(payload, actor, workspace) { const type=clean(payload.documentType ?? payload.document_type).toUpperCase(); if(!TYPES.has(type)) throw new ApiError(400,'Document type is invalid.'); const userId=actorId(actor); const lines=normalizeLines(payload.lines); const client=await pool.connect(); try { await client.query('begin'); const number=await allocateDocumentNumber(client,workspace.storeId,type); const result=await client.query(`insert into inventory_documents(tenant_id,store_id,document_type,document_number,created_by,note,effective_at,original_document_id) values($1,$2,$3::inventory_document_type,$4,$5,$6,$7,$8) returning *`,[workspace.tenantId,workspace.storeId,type,number,userId,clean(payload.note)||null,payload.effectiveAt ?? payload.effective_at ?? null,payload.originalDocumentId ?? payload.original_document_id ?? null]); const doc=result.rows[0]; await replaceLines(client,doc,lines); await addEvent(client,{documentId:doc.id,actorId:userId,type:'CREATED',toStatus:'DRAFT',revision:1,payload:{documentNumber:number,documentType:type,lineCount:lines.length}}); await client.query('commit'); return doc; } catch(e){await client.query('rollback').catch(()=>undefined);throw e;} finally{client.release();} }
export async function updateDocument(id,payload,actor,workspace) { const userId=actorId(actor); const client=await pool.connect(); try{await client.query('begin');const doc=await loadDocument(client,id,workspace.storeId,true);if(doc.created_by!==userId||!EDITABLE.has(doc.status)) throw new ApiError(403,'Only the creator may edit a Draft or Rejected document.');if(payload.note!==undefined) await client.query(`update inventory_documents set note=$1,updated_at=now() where id=$2`,[clean(payload.note)||null,id]);if(payload.lines!==undefined) await replaceLines(client,doc,normalizeLines(payload.lines));await addEvent(client,{documentId:id,actorId:userId,type:'DRAFT_UPDATED',fromStatus:doc.status,toStatus:doc.status,revision:doc.revision,payload:{linesChanged:payload.lines!==undefined}});await client.query('commit');return await getDocumentById(id,workspace.storeId);}catch(e){await client.query('rollback').catch(()=>undefined);throw e;}finally{client.release();} }
export async function cancelDocument(id,actor,workspace) { const userId=actorId(actor); const client=await pool.connect();try{await client.query('begin');const doc=await loadDocument(client,id,workspace.storeId,true);if(doc.created_by!==userId||doc.status!=='DRAFT')throw new ApiError(403,'Only the creator may cancel a Draft document.');await client.query(`update inventory_documents set status='CANCELLED',cancelled_by=$1,cancelled_at=now(),updated_at=now() where id=$2`,[userId,id]);await addEvent(client,{documentId:id,actorId:userId,type:'CANCELLED',fromStatus:'DRAFT',toStatus:'CANCELLED',revision:doc.revision});await client.query('commit');return getDocumentById(id,workspace.storeId);}catch(e){await client.query('rollback').catch(()=>undefined);throw e;}finally{client.release();} }
export async function submitDocument(id,actor,workspace) { const userId=actorId(actor); const client=await pool.connect();try{await client.query('begin');const doc=await loadDocument(client,id,workspace.storeId,true);if(doc.created_by!==userId||!EDITABLE.has(doc.status))throw new ApiError(403,'Only the creator may submit a Draft or Rejected document.');const nextRevision=doc.status==='REJECTED'?doc.revision+1:doc.revision;const lines=await loadLines(client,id);await validateDocumentForSubmission(doc,lines,client);await client.query(`update inventory_document_items set item_name_snapshot=current_item_name,base_unit_snapshot=current_base_unit,storage_location_name_snapshot=current_location_name,updated_at=now() from (select di.id,coalesce(i.name,p.name) current_item_name,bu.name current_base_unit,sl.name current_location_name from inventory_document_items di join inventory_items ii on ii.id=di.inventory_item_id left join ingredients i on i.id=ii.ingredient_id left join products p on p.id=ii.product_id left join inventory_item_units bu on bu.inventory_item_id=ii.id and bu.is_base left join storage_locations sl on sl.id=ii.storage_location_id where di.document_id=$1) snap where inventory_document_items.id=snap.id`,[id]);const snapshot=await buildDocumentSubmissionSnapshot(doc,lines,nextRevision,client);const hash=hashDocumentSubmissionSnapshot(snapshot);await client.query(`update inventory_documents set status='PENDING_APPROVAL',revision=$1,submitted_by=$2,submitted_at=now(),rejection_reason=null,updated_at=now() where id=$3`,[nextRevision,userId,id]);await addEvent(client,{documentId:id,actorId:userId,type:'SUBMITTED',fromStatus:doc.status,toStatus:'PENDING_APPROVAL',revision:nextRevision,hash,payload:{snapshot}});await client.query('commit');return getDocumentById(id,workspace.storeId);}catch(e){await client.query('rollback').catch(()=>undefined);throw e;}finally{client.release();} }
export async function rejectDocument(id,actor,workspace,reason) { const userId=actorId(actor); if(!(workspace.isOwner||workspace.role==='MANAGER'))throw new ApiError(403,'Manager or Owner role is required.');const text=clean(reason);if(!text)throw new ApiError(400,'Rejection reason is required.');const client=await pool.connect();try{await client.query('begin');const doc=await loadDocument(client,id,workspace.storeId,true);if(doc.status!=='PENDING_APPROVAL')throw new ApiError(409,'Document is not pending approval.');await client.query(`update inventory_documents set status='REJECTED',rejected_by=$1,rejected_at=now(),rejection_reason=$2,updated_at=now() where id=$3`,[userId,text,id]);await addEvent(client,{documentId:id,actorId:userId,type:'REJECTED',fromStatus:'PENDING_APPROVAL',toStatus:'REJECTED',revision:doc.revision,reason:text});await client.query('commit');return getDocumentById(id,workspace.storeId);}catch(e){await client.query('rollback').catch(()=>undefined);throw e;}finally{client.release();} }
export async function approveDocumentWithPosting({documentId,actor,workspace,postingHandler,client:callerClient}) { if(typeof postingHandler!=='function')throw new ApiError(409,'DOCUMENT_TYPE_NOT_OPERATIONAL');if(!(workspace.isOwner||workspace.role==='MANAGER'))throw new ApiError(403,'Manager or Owner role is required.');const userId=actorId(actor),ownsClient=!callerClient,client=callerClient||await pool.connect();try{if(ownsClient)await client.query('begin');const doc=await loadDocument(client,documentId,workspace.storeId,true);if(doc.status!=='PENDING_APPROVAL')throw new ApiError(409,'Document is not pending approval.');const lines=await loadLines(client,doc.id);const submitted=await client.query(`select content_hash from inventory_document_events where document_id=$1 and event_type='SUBMITTED' and document_revision=$2 order by created_at desc,id desc limit 1`,[doc.id,doc.revision]);if(!submitted.rows[0]||submitted.rows[0].content_hash!==hashDocumentSubmissionSnapshot(await buildDocumentSubmissionSnapshot(doc,lines,doc.revision,client,true)))throw new ApiError(409,'Submitted document content no longer matches its reviewed revision.');const postingResult=await postingHandler(client,doc,lines),postingMetadata=postingResult?.approvalEventMetadata||{};await client.query(`update inventory_documents set status='APPROVED',approved_by=$1,approved_at=now(),posted_at=now(),updated_at=now() where id=$2`,[userId,doc.id]);await addEvent(client,{documentId:doc.id,actorId:userId,type:'APPROVED',fromStatus:'PENDING_APPROVAL',toStatus:'APPROVED',revision:doc.revision,payload:{posting:postingMetadata}});await addEvent(client,{documentId:doc.id,actorId:userId,type:'POSTED',fromStatus:'APPROVED',toStatus:'APPROVED',revision:doc.revision,payload:{posting:postingMetadata}});if(ownsClient)await client.query('commit');return getDocumentById(doc.id,workspace.storeId);}catch(e){if(ownsClient)await client.query('rollback').catch(()=>undefined);throw e;}finally{if(ownsClient)client.release();} }
export async function listDocuments(filters,storeId) { const params=[storeId];const c=['d.store_id=$1'];if(clean(filters.search)){params.push(`%${clean(filters.search)}%`);c.push(`d.document_number ilike $${params.length}`);}for(const [key,col] of [['documentType','document_type'],['status','status'],['creatorId','created_by'],['approverId','approved_by']])if(clean(filters[key])){params.push(clean(filters[key]));c.push(`d.${col}=$${params.length}`);}const limit=Math.min(Math.max(Number(filters.limit)||50,1),200),offset=Math.max(Number(filters.offset)||0,0);params.push(limit,offset);const r=await query(`select d.*,coalesce(cu.full_name,cu.username) creator_name,coalesce(au.full_name,au.username) approver_name from inventory_documents d join app_users cu on cu.id=d.created_by left join app_users au on au.id=d.approved_by where ${c.join(' and ')} order by d.created_at desc,d.id desc limit $${params.length-1} offset $${params.length}`,params);return r.rows; }
export async function getDocumentById(id,storeId){const doc=await query(`select d.*,coalesce(cu.full_name,cu.username) creator_name,coalesce(su.full_name,su.username) submitter_name,coalesce(au.full_name,au.username) approver_name,coalesce(ru.full_name,ru.username) rejector_name from inventory_documents d join app_users cu on cu.id=d.created_by left join app_users su on su.id=d.submitted_by left join app_users au on au.id=d.approved_by left join app_users ru on ru.id=d.rejected_by where d.id=$1 and d.store_id=$2`,[id,storeId]);if(!doc.rows[0])throw new ApiError(404,'Inventory document not found.');const lines=await loadLines({query},id);return {...doc.rows[0],lines};}
export async function listDocumentEvents(id,storeId){await getDocumentById(id,storeId);return (await query(`select e.*,coalesce(u.full_name,u.username) actor_name from inventory_document_events e join app_users u on u.id=e.actor_id where e.document_id=$1 order by e.created_at,e.id`,[id])).rows;}
