import { describe, expect, it } from 'vitest';
import { readFile } from 'node:fs/promises';

const serviceFile = new URL('../src/modules/inventory/goods-receipt.service.js', import.meta.url);
const routesFile = new URL('../src/modules/inventory/inventory.routes.js', import.meta.url);
const controllerFile = new URL('../src/modules/inventory/goods-receipt.controller.js', import.meta.url);
const migrationFile = new URL('../src/seed/run_inventory_phase6_goods_receipt_migration.js', import.meta.url);
const source = await readFile(serviceFile, 'utf8');
const routes = await readFile(routesFile, 'utf8');
const controller = await readFile(controllerFile, 'utf8');
const migration = await readFile(migrationFile, 'utf8');

describe('Goods Receipt 6A.1 implementation contracts', () => {
  it('has a focused draft-create service and PN number allocation', () => { expect(source).toContain('createGoodsReceiptDraft'); expect(source).toContain("allocateDocumentNumber(client, workspace.storeId, 'GOODS_RECEIPT')"); });
  it('creates a DRAFT document and matching typed details', () => { expect(source).toContain("document_type,document_number,created_by,note,effective_at"); expect(source).toContain('insert into inventory_receipt_line_details'); });
  it('uses a single transaction for draft create, edit, and submission', () => { expect((source.match(/await client\.query\('begin'\)/g) || []).length).toBeGreaterThanOrEqual(4); expect((source.match(/await client\.query\('rollback'\)/g) || []).length).toBeGreaterThanOrEqual(4); });
  it('rejects Product receipt with its explicit Phase 6A.1 code', () => { expect(source).toContain('GOODS_RECEIPT_PRODUCT_NOT_ENABLED_YET'); });
  it('rejects Preparation receipt and accepts Raw Ingredient only', () => { expect(source).toContain('GOODS_RECEIPT_PREPARATION_NOT_ALLOWED'); expect(source).toContain("item.item_type !== 'RAW_INGREDIENT'"); });
  it('validates duplicate item, required fields, positive quantity, and nonnegative value', () => { expect(source).toContain('GOODS_RECEIPT_DUPLICATE_ITEM'); expect(source).toContain('GOODS_RECEIPT_LINE_FIELDS_REQUIRED'); expect(source).toContain("requirePositiveDecimal(line.enteredQuantity"); expect(source).toContain("requireNonNegativeDecimal(line.totalPurchaseValue"); });
  it('validates store ownership, active catalog state, base unit, and selected purchase unit', () => { expect(source).toContain('GOODS_RECEIPT_ITEM_NOT_IN_STORE'); expect(source).toContain('GOODS_RECEIPT_ITEM_INACTIVE'); expect(source).toContain('convertToBase({ inventoryItemId'); expect(source).toContain('inventoryBaseUnitRequiredError'); });
  it('deletes receipt details before generic lines during draft replacement', () => { const details = source.indexOf('delete from inventory_receipt_line_details'); const generic = source.indexOf('delete from inventory_document_items where document_id=$1', details); expect(details).toBeGreaterThan(-1); expect(generic).toBeGreaterThan(details); });
  it('limits edits and submits to the creator in Draft or Rejected status', () => { expect(source).toContain("const EDITABLE = new Set(['DRAFT', 'REJECTED'])"); expect((source.match(/document\.created_by !== userId \|\| !EDITABLE\.has\(document\.status\)/g) || []).length).toBe(2); });
  it('increments the revision only when a rejected receipt is resubmitted', () => { expect(source).toContain("document.status === 'REJECTED' ? Number(document.revision) + 1"); });
  it('freezes conversion, typed financial values, and display snapshots on submit', () => { expect(source).toContain('conversion_factor_to_base_snapshot'); expect(source).toContain('conversion_path_snapshot'); expect(source).toContain('converted_base_quantity'); expect(source).toContain('derived_incoming_unit_cost'); expect(source).toContain('item_name_snapshot=$1,base_unit_snapshot=$2,storage_location_name_snapshot=$3'); });
  it('reads business DTOs and produces a non-mutating pending review projection', () => { expect(source).toContain('projectedQuantity'); expect(source).toContain('projectedWAC'); expect(source).toContain('initialValuationRequired'); expect(source).toContain('calculateGoodsReceiptValuation'); });
  it('uses the Phase 3 rejection event flow and keeps Phase 6A.1 free of direct balance SQL', () => { expect(source).toContain("type: 'REJECTED'"); expect(source).toContain('approveDocumentWithPosting'); expect(source).toContain('postInventoryMovements'); expect(source).not.toContain('quantity_on_hand='); });
  it('registers typed snapshot and validator extensions', () => { expect(source).toContain("registerDocumentValidator('GOODS_RECEIPT'"); expect(source).toContain("registerSubmissionSnapshotExtension('GOODS_RECEIPT'"); expect(source).toContain('hashGoodsReceiptSubmissionSnapshot'); });
  it('mounts the typed receipt lifecycle and manager/owner-only approve route', () => { expect(routes).toContain("router.post('/goods-receipts', createGoodsReceipt)"); expect(routes).toContain("router.get('/goods-receipts/:id', getGoodsReceiptById)"); expect(routes).toContain("router.patch('/goods-receipts/:id', updateGoodsReceipt)"); expect(routes).toContain("router.post('/goods-receipts/:id/submit', submitGoodsReceiptDocument)"); expect(routes).toContain("router.post('/goods-receipts/:id/reject', rejectGoodsReceiptDocument)"); expect(routes).toContain("router.post('/goods-receipts/:id/approve', requireStoreManager(), approveGoodsReceiptDocument)"); });
  it('keeps HTTP mapping in a focused controller', () => { expect(controller).toContain('createGoodsReceiptDraft'); expect(controller).toContain('asyncHandler'); expect(controller).not.toContain('client.query'); });
  it('targets the existing unexecuted typed-detail schema, including future 6A.2 columns', () => { expect(migration).toContain('create table if not exists inventory_receipt_line_details'); expect(migration).toContain('initial_valuation_applied'); expect(migration).toContain('resulting_unit_cost_snapshot'); });
});

describe('Goods Receipt 6A.2 approval/posting implementation contracts', () => {
  it('uses the Phase 3 approval primitive instead of approving before posting', () => { expect(source).toContain('approveDocumentWithPosting({ documentId: id'); expect(source).toContain('postingHandler: async'); });
  it('accepts only approval-time bootstrap controls', () => { expect(source).toContain('GOODS_RECEIPT_APPROVAL_EDITS_FORBIDDEN'); expect(source).toContain('initialValuationLineIds'); });
  it('uses frozen converted quantity, purchase value, and incoming cost', () => { expect(source).toContain('frozenReceiptLine'); expect(source).toContain('Frozen converted quantity'); expect(source).toContain('Frozen purchase value'); expect(source).toContain('Frozen incoming unit cost'); });
  it('uses deterministic per-line receipt posting keys', () => { expect(source).toContain('document:${document.id}:line:${line.document_item_id}:receipt'); expect(source).toContain("movementType: 'RECEIPT_IN'"); });
  it('delegates sorted locks and balance persistence to the posting service', () => { expect(source).toContain('postInventoryMovements(client'); expect(source).toContain('prepareLockedMovements'); expect(source).not.toContain('update inventory_items set quantity_on_hand'); });
  it('revalidates locked item Store, raw type, ingredient status, and preparation exclusion', () => { expect(source).toContain('GOODS_RECEIPT_ITEM_NO_LONGER_ELIGIBLE'); expect(source).toContain("item.item_type !== 'RAW_INGREDIENT'"); expect(source).toContain('item.ingredient_deleted_at'); expect(source).toContain('item.ingredient_is_preparation'); });
  it('rejects negative inventory and requires explicit bootstrap confirmation atomically', () => { expect(source).toContain('NEGATIVE_INVENTORY_REQUIRES_RECONCILIATION'); expect(source).toContain('INITIAL_INVENTORY_VALUATION_REQUIRED'); expect(source).toContain('INITIAL_VALUATION_LINE_NOT_IN_RECEIPT'); });
  it('writes normal and bootstrap valuation details into receipt snapshots', () => { expect(source).toContain('persistApprovalSnapshots'); expect(source).toContain('initial_existing_quantity_snapshot'); expect(source).toContain('resulting_inventory_value_snapshot'); expect(source).toContain('resulting_unit_cost_snapshot'); });
  it('records separate purchase spend and total bootstrap valuation metadata', () => { expect(source).toContain('purchaseValue: line.purchaseValue'); expect(source).toContain('totalValuationDelta'); expect(source).toContain('INITIAL_VALUATION_BOOTSTRAP'); });
  it('runs recipe-cost recalculation in the same transaction after posting', () => { expect(source).toContain('await recalculateDependentRecipeCosts(client'); expect(source).toContain('sourceInventoryItemIds'); });
  it('adds generic approval event metadata without hard-coding receipt fields in Phase 3', async () => { const documentService = await readFile(new URL('../src/modules/inventory/inventory-document.service.js', import.meta.url), 'utf8'); expect(documentService).toContain('postingResult?.approvalEventMetadata'); expect(documentService).not.toContain('initialValuationValue'); });
  it('persists approved historical actuals and approval actor/time in the receipt DTO', () => { expect(source).toContain('approvedActuals'); expect(source).toContain('approver_name'); expect(source).toContain('postedAt: document.posted_at'); });
  it('preserves hash verification across focused submit and generic approve paths', async () => { const documentService = await readFile(new URL('../src/modules/inventory/inventory-document.service.js', import.meta.url), 'utf8'); expect(source).toContain('buildDocumentSubmissionSnapshot(document, lines, revision, client)'); expect(documentService).toContain('hashDocumentSubmissionSnapshot(await buildDocumentSubmissionSnapshot'); expect(documentService).toContain('buildSubmittedDocumentSnapshot'); });
  it('does not create legacy stock transactions or enable Product receipt', () => { expect(source).not.toContain('stock_transactions'); expect(source).toContain('GOODS_RECEIPT_PRODUCT_NOT_ENABLED_YET'); });
  it('uses only columns present in the unexecuted Phase 6A receipt-detail migration', () => { for (const column of ['initial_existing_quantity_snapshot', 'initial_valuation_unit_cost_snapshot', 'initial_valuation_value_snapshot', 'resulting_quantity_snapshot', 'resulting_inventory_value_snapshot', 'resulting_unit_cost_snapshot']) expect(migration).toContain(column); });
});
